In [1]:
import pandas as pd

In [2]:
neurons = pd.read_csv("../data/neurons.csv.gz")
print(neurons.shape)
neurons.head()

(139255, 10)

,root_id,group,nt_type,nt_type_score,da_avg,ser_avg,gaba_avg,glut_avg,ach_avg,oct_avg
0,720575940596125868,LO.LOP,ACH,0.57,0.03,0.00,0.05,0.28,0.57,0.07
1,720575940597856265,ME,ACH,0.85,0.01,0.00,0.03,0.04,0.85,0.07
2,720575940597944841,ME.LO,ACH,0.82,0.02,0.00,0.01,0.05,0.82,0.09
3,720575940598267657,ME,GABA,0.74,0.01,0.01,0.74,0.19,0.03,0.02
4,720575940599333574,ME,ACH,0.61,0.02,0.00,0.13,0.13,0.61,0.11

In [3]:
classification = pd.read_csv("../data/classification.csv.gz")
print(classification.shape)
cell_types=pd.read_csv("../data/consolidated_cell_types.csv.gz")
print(cell_types.shape)
cell_stats=pd.read_csv("../data/cell_stats.csv.gz")
print(cell_stats.shape)
connections=pd.read_csv("../data/connections_princeton.csv.gz")
print(connections.shape)

(139255, 8)
(138327, 3)
(139246, 4)
(5342446, 5)

In [4]:
classification.head()

,root_id,flow,super_class,class,sub_class,hemilineage,side,nerve
0,720575940599457990,intrinsic,optic,optic_lobe_intrinsic,t4_neuron,NaN,right,NaN
1,720575940599763910,intrinsic,optic,optic_lobe_intrinsic,t5_neuron,NaN,right,NaN
2,720575940600623020,intrinsic,optic,optic_lobe_intrinsic,distal_medulla,NaN,right,NaN
3,720575940602309600,afferent,sensory_ascending,AN,SA_DMT_DMetaN,NaN,right,CV
4,720575940602564320,intrinsic,central,Kenyon_Cell,KCg,MBp4,right,NaN

In [5]:
cell_types.head()

              root_id primary_type additional_type(s)
0  720575940599457990          T4b                NaN
1  720575940599763910          T5b                NaN
2  720575940600623020         Dm3q                NaN
3  720575940602564320        KCg-m                NaN
4  720575940602720940        JO-CA                NaN

In [6]:
cell_stats.head()

              root_id  length_nm     area_nm       size_nm
0  720575940596125868     396840   628299136   37616302080
1  720575940597856265    1184013  1634424448  100004290560
2  720575940597944841     784742  1022307072   58954229760
3  720575940598267657    1645960  2346787840  140744601600
4  720575940599333574     575383  1366784768  111170764800

In [7]:
connections.head()

          pre_root_id        post_root_id neuropil  syn_count nt_type
0  720575940625363947  720575940623224444     ME_L         12    GABA
1  720575940630432382  720575940618518557     ME_L         67     ACH
2  720575940627314521  720575940626337738     ME_L         10    GABA
3  720575940620280405  720575940620204726     ME_L         15     ACH
4  720575940636942447  720575940613789411     LA_L          1    GLUT